### ISSUE TITLE
Display 'tags' for each blog post in the index listing.

### ISSUE THREAD

**Issue by kennyklee** [kennyklee/blog#6]
As a reader, I want to be able to filter the types of blog posts that are listed on the homepage, so that I can view only the topic that I'm interested in.

tags=used by author to categorize topics
keywords=for search engines

Use 'tags' and display within the blog post listing (index).
Don't use 'keywords' for now.

**Proposed topics:**

* Personal
* Learning
*  #Technology

**To-Do**

- [x] Check each blog post for tags.
- [x] HTML of the tags in front-page
- [ ] Style (CSS) the buttons

**Comment by kennyklee** [comment]
Checked each blog post for tags and fixed it.

**Comment by kennyklee** [comment]
Done.  https://cl.ly/2r0g3J0h3u40

See screenshot for the tag look and feel.
